[package]
name = "vectrex-rs"
version = "0.1.0"
authors = ["Sebastian Reinhard <sebastian@sebbert.me>"]

[features]
default = []
compare = []

[dependencies]
log = "0.3.*"
env_logger = "0.4.*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"